# Generated by Django 4.2 on 2023-04-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
