# Generated by Django 4.2 on 2023-04-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_restaurants', '0002_rename_speciality_cuisine_restaurant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisines'},
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='speciality',
            new_name='cuisine',
        ),
    ]
