# Generated by Django 4.2 on 2023-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_restaurants', '0003_alter_cuisine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
