# Generated by Django 4.2 on 2023-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_restaurants', '0004_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
