# Generated by Django 4.2 on 2023-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_restaurants', '0005_alter_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='slug',
            field=models.SlugField(default='default', max_length=30),
        ),
    ]
